# Generated by Django 4.2.11 on 2024-05-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
